spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:atquilDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.springframework.security: trace


jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
