spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:atquilDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop #Create new db everytime we start the application