# Need to create client credential on respective application

### Please use your own client-id and client scerete

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
          google:
            client-id: 
            client-secret: 
